[build-system]
requires = ["setuptools>=46.1.0", "setuptools_scm[toml]>=5"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"

[project]
name = "mnist_trainer"
version = "0.1.0"
# Eliminar el valor estático de description, readme, license, authors y classifiers
# description = "Add a short description here!"  # elimina esta línea
# readme = "README.md"  # elimina esta línea
# license = { text = "MIT" }  # elimina esta línea
# authors = [{ name = "embolao" }]  # elimina esta línea
# classifiers = [ ... ]  # elimina esta línea

# Mantén la sección dynamic
dynamic = ["description", "readme", "license", "authors", "classifiers"]

[project.scripts]
mnist-train = "mnist_trainer.train:train_model"
